---
 homebrew_cask_packages:
  - alfred
  - caffeine
  - dockertoolbox
  - dropbox
  - virtualbox
  - vagrant
  - divvy
  - flux
  - gitup
  - grandperspective
  - intellij-idea-ce
  - firefox
  - evernote
  - gimp
  - google-chrome
  - spotify
  - iterm2
  - java
  - slack
  - steam
  - skype
  - macvim
  - tunnelblick
  - sublime-text3
